version: "3"

services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
